In [2]:
import os
import csv
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

jfish_df = pd.read_csv('CoJFd.csv')
jfish_df.head()

C:\Users\kohle\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3063: DtypeWarning: Columns (6,7,8,10,11,21,22,23,24,25,26,27,28,29,30,31,32,34,36) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,project_title,sub_project_title,owner_dataset,contact,location_name,date,year,month,day,time_local,...,density,density_integrated,biovolume,biovolume_integrated,weight_wet,weight_dry,presence_absence,study_type,accompanying_ancillary_data,catch_per_effort
0,dimensionless,dimensionless,dimensionless,dimensionless,dimensionless,variable,unitless,MM,DD,HH:MM:SS,...,unknown,unknown,milliliters/meter^3,milliliters/meter^2,grams/meter^3,grams/meter^3,dimensionless,dimensionless,dimensionless,kilograms per hectare
1,ChespkBay_Prog,ChespkBay_Prog,USEPA_ChespkBay_Prog,Johnson_J,Main_Pier_at_Chesapeake_Biological_Laboratory;...,10/11/1970,1970,10,11,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,present,monitoring_project,no,NaN
2,ChespkBay_Prog,ChespkBay_Prog,USEPA_ChespkBay_Prog,Johnson_J,Main_Pier_at_Chesapeake_Biological_Laboratory;...,10/18/1970,1970,10,18,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,present,monitoring_project,no,NaN
3,ChespkBay_Prog,ChespkBay_Prog,USEPA_ChespkBay_Prog,Johnson_J,Main_Pier_at_Chesapeake_Biological_Laboratory;...,10/25/1970,1970,10,25,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,present,monitoring_project,no,NaN
4,ChespkBay_Prog,ChespkBay_Prog,USEPA_ChespkBay_Prog,Johnson_J,Main_Pier_at_Chesapeake_Biological_Laboratory;...,10/4/1970,1970,10,4,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,present,monitoring_project,no,NaN

In [3]:
jfish_df.columns

Index(['project_title', 'sub_project_title', 'owner_dataset', 'contact',
       'location_name', 'date', 'year', 'month', 'day', 'time_local',
       'latitude', 'longitude', 'taxon', 'rank_phylum', 'rank_class',
       'rank_order', 'rank_family', 'rank_genus', 'rank_species', 'data_type',
       'collection_method', 'net_opening', 'net_mesh', 'depth', 'depth_upper',
       'depth_lower', 'count_actual', 'density', 'density_integrated',
       'biovolume', 'biovolume_integrated', 'weight_wet', 'weight_dry',
       'presence_absence', 'study_type', 'accompanying_ancillary_data',
       'catch_per_effort'],
      dtype='object')

In [12]:
jfish_df['rank_type'] = jfish_df['rank_family'] + jfish_df['rank_genus']

better_df = jfish_df[['location_name','date', 'rank_type', 'count_actual', 'presence_absence']].copy()
better_df.head()

,location_name,date,rank_type,count_actual,presence_absence
0,dimensionless,variable,dimensionlessdimensionless,dimensionless,dimensionless
1,Main_Pier_at_Chesapeake_Biological_Laboratory;...,10/11/1970,PelagiidaeChrysaora,120,present
2,Main_Pier_at_Chesapeake_Biological_Laboratory;...,10/18/1970,PelagiidaeChrysaora,40,present
3,Main_Pier_at_Chesapeake_Biological_Laboratory;...,10/25/1970,PelagiidaeChrysaora,6,present
4,Main_Pier_at_Chesapeake_Biological_Laboratory;...,10/4/1970,PelagiidaeChrysaora,36,present

In [13]:
better_df.dropna()
better_df

,location_name,date,rank_type,count_actual,presence_absence
0,dimensionless,variable,dimensionlessdimensionless,dimensionless,dimensionless
1,Main_Pier_at_Chesapeake_Biological_Laboratory;...,10/11/1970,PelagiidaeChrysaora,120,present
2,Main_Pier_at_Chesapeake_Biological_Laboratory;...,10/18/1970,PelagiidaeChrysaora,40,present
3,Main_Pier_at_Chesapeake_Biological_Laboratory;...,10/25/1970,PelagiidaeChrysaora,6,present
4,Main_Pier_at_Chesapeake_Biological_Laboratory;...,10/4/1970,PelagiidaeChrysaora,36,present
...,...,...,...,...,...
372975,Whiterocks_N._Antrim,5/12/2011,RhizostomatidaeRhizostoma,NaN,absent
372976,Whiterocks_N._Antrim,5/12/2011,CyaneidaeCyanea,NaN,absent
372977,Whiterocks_N._Antrim,5/12/2011,PelagiidaeChrysaora,NaN,absent
372978,Whiterocks_N._Antrim,5/12/2011,PelagiidaePelagia,NaN,absent
372979,Whiterocks_N._Antrim,5/12/2011,UlmaridaeAurelia,NaN,absent

In [14]:
better_df.to_csv('CoJFd.csv')